name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: 'Publish on the development server'

    steps:
    - name: Create and use production server Docker Context
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        command: echo "dadaya"
