name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: 'Publish on the development server'

    steps:
    - name: Create and use production server Docker Context
      uses: actions/checkout@v4
      env:
        CA: ${{ secrets.CA_FILE }}
        CERT: ${{ secrets.CERT_FILE }}
        KEY: ${{ secrets.KEY_FILE }}
    - run: |
        docker context create deploing --docker "host=tcp://sun-diego.ru:2376,ca=$CA,cert=$CERT,key=$KEY";
        docker context use deploing;
        docker ps;
