name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: 'Publish on the development server'

    steps:
    - name: Create and use production server Docker Context
      uses: actions/checkout@v4
      env:
#        CA: ${{ secrets.CA_FILE }}
#        CERT: ${{ secrets.CERT_FILE }}
#        KEY: ${{ secrets.KEY_FILE }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - run: |
        docker context create --docker="host=ssh://root@sun-diego.ru:22" dev
        docker context use dev;
        docker ps;
