name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: arwynfr/actions-docker-context@v2
      with:
        docker_host: 'ssh://root@sun-diego.ru'
        context_name: 'github_cicd'
        ssh_cert: ${{ secrets.SSH_CERT }}
        ssh_key: ${{ secrets.SSH_KEY }}
    - run: |
        docker --context github_cicd ps
#        docker --context github_cicd compose down;
#        docker --context github_cicd compose build ./docker-compose.yml;
#        docker --context github_cicd compose up -d;
#        docker --context github_cicd prune -all --force;
#        docker-compose build ./docker-compose.yml;
#        docker-compose up -d;
#        docker system prune --all --force;
